# Generated by Django 4.2.8 on 2024-05-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_first_name_alter_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_quality', models.IntegerField(choices=[(1, 'Bad'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Best')])),
                ('design_looks', models.IntegerField(choices=[(1, 'Bad'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Best')])),
                ('time', models.IntegerField(choices=[(1, 'Too Late'), (2, 'Late'), (3, 'Same Time'), (4, 'On Time'), (5, 'Before Time')])),
                ('behaviour', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')])),
                ('builder_photo', models.ImageField(blank=True, null=True, upload_to='builder_photos')),
                ('past_experience_years', models.IntegerField()),
                ('number_of_projects_done', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default_photo.jpg', upload_to='project_photos/')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.builder')),
            ],
        ),
    ]
