# Generated by Django 4.2.8 on 2024-05-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_builder_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='bathware',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='builder',
            name='cement_company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='builder',
            name='contact_no',
            field=models.CharField(default='unknown', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builder',
            name='paint',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='builder',
            name='sanitary_ware',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='builder',
            name='tmt_bar',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='builder',
            name='time',
            field=models.IntegerField(choices=[(1, 'Too Late'), (2, 'Late'), (3, 'some late'), (4, 'On Time'), (5, 'Before Time')]),
        ),
    ]
