# Generated by Django 4.2.8 on 2024-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_builder_bathware_builder_cement_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='price_cost_without_material',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
