# Generated by Django 4.2.8 on 2024-05-11 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_builder_price_cost_without_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floors', models.IntegerField()),
                ('area_per_floor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('with_material', models.BooleanField(default=True)),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.builder')),
            ],
        ),
    ]
