# Generated by Django 4.2.8 on 2024-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_houseestimation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseestimation',
            name='area_per_floor',
        ),
        migrations.AddField(
            model_name='houseestimation',
            name='area_per_floor_list',
            field=models.CharField(default='[]', max_length=1000),
            preserve_default=False,
        ),
    ]
