# Generated by Django 4.2.8 on 2024-05-17 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_houseestimation_area_per_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_breadth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plot_view', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=100)),
                ('no_of_floors', models.IntegerField()),
                ('no_of_master_bedroom', models.IntegerField()),
                ('kid_room_required', models.BooleanField(default=False)),
                ('guest_room_required', models.BooleanField(default=False)),
                ('kitchen_location', models.CharField(choices=[('Ground Floor', 'Ground Floor'), ('First Floor', 'First Floor'), ('All Floors', 'All Floors')], max_length=100)),
                ('balcony_required', models.BooleanField(default=False)),
                ('parking_facility', models.BooleanField(default=False)),
                ('garden_provision', models.BooleanField(default=False)),
                ('bathroom_size_choice', models.CharField(choices=[('Big', 'Big'), ('Standard', 'Standard'), ('Small', 'Small')], max_length=100)),
                ('front_site', models.CharField(choices=[('road', 'Road'), ('other', 'Other property')], max_length=100)),
                ('back_site', models.CharField(choices=[('road', 'Road'), ('other', 'Other property')], max_length=100)),
                ('right_site', models.CharField(choices=[('road', 'Road'), ('other', 'Other property')], max_length=100)),
                ('left_site', models.CharField(choices=[('road', 'Road'), ('other', 'Other property')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
